---
name: Ansible collection docs build (PR)
on:
  workflow_call:
    inputs:
      collection-name:
        description: The collection name in the form namespace.collection.
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      collection-path:
        description: This is the relative path component of the collection in question, for example community/general.
        required: false
        type: string
      python:
        description: The version of Python to install.
        required: false
        type: string
        default: '3.9'
      ansible-ref:
        description: The ref from which to install ansible, for example "stable-2.12" or "milestone".
        required: false
        type: string
        default: milestone
      init-dest-dir:
        description: A directory relative to the checkout where the init process has already been run.
        required: false
        type: string
      artifact-name:
        description: The name of the artifact to upload.
        required: false
        type: string
        default: ${{ github.event.repository.name }}_docs_${{ github.event.pull_request.head.sha }}
      diff-size-limit:
        description: The max size of the diff, past which it will be truncated.
        required: false
        type: number
        default: 60000
      sort-files:
        description: If true, sort the trimmed and rendered list of files.
        required: false
        default: true
        type: boolean
      render-file-line:
        description: |
          A template used to render each line of the file list as markdown. This will be processed as a JavaScript regex replace string,
          and the following named capture groups can be referenced:
          - $<status> -- the single character "status" letter in the file list, like "A" or an added file or "M" for a modified file.
          - $<path_stub> -- the part of the path that will be discarded in the "trimmed" file list.
          - $<path_tail> -- the relative part of the path; this can be used to concatenate to a URL to create links to the published site.

          Note that literal $ characters must be escaped as $$ and literal backslashes must be escaped as \\
        required: false
        default: '> * `$<status>` $<path_tail>'
        type: string
      render-diff-truncate-text:
        description: Markdown text to be used if the diff text was truncated. It will be available in the render-diff template.
        required: false
        default: '**The diff output was truncated because it exceeded the maximum size.**'
        type: string
      render-diff:
        description: |
          A template used to render the diff output as markdown. It will be interpreted as a pseudo-JavaScript template literal and the following
          variables are available for ${var} interpolation:
          - ${diff} -- the diff text
          - ${truncated_msg} -- empty if the diff is not truncated, otherwise the value of render-diff-truncate-text
        required: false
        type: string
        default: |
          <details>
          <summary>Click to see the diff comparison.</summary>

          **NOTE:** only file modifications are shown here. New and deleted files are excluded.
          See the file list and check the published docs to see those files.

          ${truncated_msg}

          ```diff
          ${diff}
          ```

          </details>

    outputs:
      artifact-name:
        description: The same artifact name as passed in, available as an output.
        value: ${{ inputs.artifact-name }}
      artifact-url:
        description: The URL to the build artifacts.
        value: ${{ jobs.build-ansible-docs.outputs.artifact-url }}
      changed:
        description: If false, the PR does not change the documentation.
        value: ${{ jobs.build-ansible-docs.outputs.changed }}
      diff:
        description: The diff between the base and head of the PR.
        value: ${{ jobs.build-ansible-docs.outputs.diff }}
      diff-truncated:
        description: If true, the diff was truncated because it exceeded the max size.
        value: ${{ jobs.build-ansible-docs.outputs.diff-truncated }}
      diff-rendered:
        description: The markdownr rendered diff between the base and head of the PR.
        value: ${{ jobs.build-ansible-docs.outputs.diff-rendered }}
      diff-files:
        description: The raw file list from the diff output.
        value: ${{ jobs.build-ansible-docs.outputs.diff-files }}
      diff-files-trimmed:
        description: The file list from the diff with the paths trimmed.
        value: ${{ jobs.build-ansible-docs.outputs.diff-files-trimmed }}
      diff-files-rendered:
        description: The markdown rendered file list from the diff.
        value: ${{ jobs.build-ansible-docs.outputs.diff-files-rendered }}

jobs:
  build-ansible-docs:
    name: Build Ansible Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-url: ${{ steps.build-head.outputs.artifact-url }}
      changed: ${{ steps.build-base.outputs.hash != steps.build-head.outputs.hash }}
      diff: ${{ steps.diff.outputs.diff }}
      diff-truncated: ${{ steps.diff.outputs.truncated }}
      diff-rendered: ${{ steps.diff.outputs.diff-rendered }}
      diff-files: ${{ steps.diff.outputs.files-raw }}
      diff-files-trimmed: ${{ steps.diff.outputs.files-trimmed }}
      diff-files-rendered: ${{ steps.diff.outputs.files-rendered }}
    steps:
      - name: Variable setup
        id: vars
        uses: actions/github-script@v5
        with:
          script: |
            const inputs = ${{ toJSON(inputs) }}
            var colpath = inputs['collection-path']
            if (colpath == '') {
                colpath = inputs['collection-name'].replace('.', '/')
            }

            core.exportVariable('ANSIBLE_COLLECTIONS_PATHS', process.env.GITHUB_WORKSPACE)

            const checkoutPath = `ansible_collections/${colpath}`

            core.setOutput('col-path', colpath)
            core.setOutput('checkout-path', checkoutPath)

            var initPath = '${{ runner.temp }}/docsbuild'
            var skipInit = false

            if (inputs['init-dest-dir'] != '') {
                initPath = `${checkoutPath}/${inputs['init-dest-dir']}`
                skipInit = true
                core.setOutput('init-dir-base', initPath)
                core.setOutput('init-dir-head', initPath)
            } else {
                core.setOutput('init-dir-base', `${initPath}/base`)
                core.setOutput('init-dir-head', `${initPath}/head`)
            }

            core.setOutput('skip-init', skipInit)

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python }}

      - name: Install Ansible
        run: pip install https://github.com/ansible/ansible/archive/${{ inputs.ansible-ref }}.tar.gz --disable-pip-version-check

      - name: Checkout BASE
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: ${{ steps.vars.outputs.checkout-path }}

      - name: Initialize the build environment (BASE)
        id: init-base
        uses: ansible-collections/community.hashi_vault/.github/actions/docs/ansible-docs-build-init@main
        with:
          collections: ${{ inputs.collection-name }}
          dest-dir: ${{ steps.vars.outputs.init-dir-base }}
          skip-init: ${{ steps.vars.outputs.skip-init }}

      - name: Build BASE
        id: build-base
        uses: ansible-collections/community.hashi_vault/.github/actions/docs/ansible-docs-build-html@main
        with:
          build-script: ${{ steps.init-base.outputs.build-script }}
          build-html: ${{ steps.init-base.outputs.build-html }}
          move-build: ${{ github.workspace }}/docsbuild/base
          artifact-upload: 'false'

      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ steps.vars.outputs.checkout-path }}

      - name: Initialize the build environment (HEAD)
        id: init-head
        uses: ansible-collections/community.hashi_vault/.github/actions/docs/ansible-docs-build-init@main
        with:
          collections: ${{ inputs.collection-name }}
          dest-dir: ${{ steps.vars.outputs.init-dir-head }}
          skip-init: ${{ steps.vars.outputs.skip-init }}

      - name: Build HEAD
        id: build-head
        uses: ansible-collections/community.hashi_vault/.github/actions/docs/ansible-docs-build-html@main
        with:
          build-script: ${{ steps.init-head.outputs.build-script }}
          build-html: ${{ steps.init-head.outputs.build-html }}
          move-build: ${{ github.workspace }}/docsbuild/head
          artifact-name: ${{ inputs.artifact-name }}

      - name: Get a diff of the changes
        if: steps.build-base.outputs.hash != steps.build-head.outputs.hash
        id: diff
        uses: ansible-collections/community.hashi_vault/.github/actions/docs/ansible-docs-build-diff@main
        with:
          build-html-a: ${{ steps.build-base.outputs.build-html }}
          build-html-b: ${{ steps.build-head.outputs.build-html }}
          diff-size-limit: ${{ inputs.diff-size-limit }}
          render-file-line: ${{ inputs.render-file-line }}
          render-diff-truncate-text: ${{ inputs.render-diff-truncate-text }}
          render-diff: ${{ inputs.render-diff }}
